name: Base workflow

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name:
        run:
    outputs:
    needs:

  test:

  quality:

  package:

